// Generated by scripts/gen-mcp-tool-names.sh from mcp/src/tools/registry.ts.
// Do not edit by hand — update MCP_TOOL_NAMES and rerun the script.

enum McpToolNames {
    static let all: [String] = [
        "get_calendar_access_status",
        "request_calendar_access",
        "list_calendars",
        "list_events",
        "get_event",
        "create_event",
        "update_event",
        "delete_event",
        "analyze_schedule",
        "find_conflicts",
        "find_free_time",
    ]
}
