/**
 * Single source of truth for MCP tool names.
 *
 * The Swift app mirrors this list in `equinox/Services/McpToolNames.generated.swift`,
 * regenerated by `scripts/gen-mcp-tool-names.sh`. Keep registrations in
 * `tools/calendars.ts` and `tools/events.ts` aligned with this array — `registry.test.ts`
 * fails if they drift.
 */
export const MCP_TOOL_NAMES = [
  "get_calendar_access_status",
  "request_calendar_access",
  "list_calendars",
  "list_events",
  "get_event",
  "create_event",
  "update_event",
  "delete_event",
  "analyze_schedule",
  "find_conflicts",
  "find_free_time",
] as const

export type McpToolName = (typeof MCP_TOOL_NAMES)[number]
