#!/bin/sh
#
# gen-mcp-tool-names.sh — generate the Swift MCP tool-name list from the
# TypeScript single source of truth (mcp/src/tools/registry.ts).
#
# The generated file is committed so `./run.sh` (app-only build) does not need
# Node. Run this whenever MCP_TOOL_NAMES changes; build-mcp.sh calls it.

set -e

cd "$(dirname "$0")/.."

REGISTRY="mcp/src/tools/registry.ts"
OUT="equinox/Services/Platform/McpToolNames.generated.swift"

if [ ! -f "${REGISTRY}" ]; then
    echo "gen-mcp-tool-names: ${REGISTRY} not found" >&2
    exit 1
fi

REGISTRY="${REGISTRY}" OUT="${OUT}" node <<'NODE'
const fs = require("fs")

const registryPath = process.env.REGISTRY
const outPath = process.env.OUT

const source = fs.readFileSync(registryPath, "utf8")
const arrayMatch = source.match(/MCP_TOOL_NAMES\s*=\s*\[([\s\S]*?)\]/)
if (!arrayMatch) {
  console.error(`gen-mcp-tool-names: MCP_TOOL_NAMES array not found in ${registryPath}`)
  process.exit(1)
}

const names = [...arrayMatch[1].matchAll(/"([^"]+)"/g)].map((m) => m[1])
if (names.length === 0) {
  console.error("gen-mcp-tool-names: no tool names parsed")
  process.exit(1)
}

const entries = names.map((name) => `        "${name}",`).join("\n")
const swift = `// Generated by scripts/gen-mcp-tool-names.sh from mcp/src/tools/registry.ts.
// Do not edit by hand — update MCP_TOOL_NAMES and rerun the script.

enum McpToolNames {
    static let all: [String] = [
${entries}
    ]
}
`

fs.writeFileSync(outPath, swift)
console.log(`gen-mcp-tool-names: wrote ${names.length} tool names to ${outPath}`)
NODE
