#!/bin/sh
#
# gen-bridge-schemas.sh — generate bridge protocol constants from
# bridge/schema/bridge-protocol.schema.json (command names, event field keys).
#
# Run whenever the schema changes; build-mcp.sh calls this script.

set -e

cd "$(dirname "$0")/.."

SCHEMA="bridge/schema/bridge-protocol.schema.json"
SWIFT_COMMANDS_OUT="equinox/Core/Generated/BridgeCommandNames.generated.swift"
SWIFT_KEYS_OUT="equinox/Core/Generated/BridgeEventFieldKeys.generated.swift"
TS_KEYS_OUT="mcp/src/schemas/generated/bridgeEventKeys.ts"

if [ ! -f "${SCHEMA}" ]; then
    echo "gen-bridge-schemas: ${SCHEMA} not found" >&2
    exit 1
fi

SCHEMA="${SCHEMA}" \
SWIFT_COMMANDS_OUT="${SWIFT_COMMANDS_OUT}" \
SWIFT_KEYS_OUT="${SWIFT_KEYS_OUT}" \
TS_KEYS_OUT="${TS_KEYS_OUT}" \
node <<'NODE'
const fs = require("fs")

const schemaPath = process.env.SCHEMA
const swiftCommandsOut = process.env.SWIFT_COMMANDS_OUT
const swiftKeysOut = process.env.SWIFT_KEYS_OUT
const tsKeysOut = process.env.TS_KEYS_OUT

const schema = JSON.parse(fs.readFileSync(schemaPath, "utf8"))
const commands = schema.commands
const required = schema.bridgeEvent.required
const optional = schema.bridgeEvent.optional
const allKeys = [...required, ...optional].sort()
const mutableFields = schema.updateMutableFields

if (!Array.isArray(commands) || commands.length === 0) {
  console.error("gen-bridge-schemas: commands array missing or empty")
  process.exit(1)
}

fs.mkdirSync(require("path").dirname(swiftCommandsOut), { recursive: true })
fs.mkdirSync(require("path").dirname(swiftKeysOut), { recursive: true })
fs.mkdirSync(require("path").dirname(tsKeysOut), { recursive: true })

const commandEntries = commands.map((name) => `        "${name}",`).join("\n")
const commandConstants = commands
  .map((name) => {
    const swiftName = name.replace(/_([a-z])/g, (_, c) => c.toUpperCase())
    return `    static let ${swiftName} = "${name}"`
  })
  .join("\n")
const swiftCommands = `// Generated by scripts/gen-bridge-schemas.sh from bridge/schema/bridge-protocol.schema.json.
// Do not edit by hand — update the schema and rerun the script.

enum BridgeCommandNames {
${commandConstants}

    static let all: [String] = [
${commandEntries}
    ]

    static let updateMutableFields: [String] = [
${mutableFields.map((f) => `        "${f}",`).join("\n")}
    ]
}
`
fs.writeFileSync(swiftCommandsOut, swiftCommands)

const swiftKeys = `// Generated by scripts/gen-bridge-schemas.sh from bridge/schema/bridge-protocol.schema.json.
// Do not edit by hand — update the schema and rerun the script.

enum BridgeEventFieldKeys {
    static let required: Set<String> = [
${required.map((k) => `        "${k}",`).join("\n")}
    ]

    static let optional: Set<String> = [
${optional.map((k) => `        "${k}",`).join("\n")}
    ]

    static let all: Set<String> = [
${allKeys.map((k) => `        "${k}",`).join("\n")}
    ]
}
`
fs.writeFileSync(swiftKeysOut, swiftKeys)

const tsKeys = `// Generated by scripts/gen-bridge-schemas.sh from bridge/schema/bridge-protocol.schema.json.
// Do not edit by hand — update the schema and rerun the script.

export const bridgeEventRequiredKeys = [
${required.map((k) => `  "${k}",`).join("\n")}
] as const

export const bridgeEventOptionalKeys = [
${optional.map((k) => `  "${k}",`).join("\n")}
] as const

export const bridgeEventAllKeys = [
${allKeys.map((k) => `  "${k}",`).join("\n")}
] as const

export const bridgeUpdateMutableFields = [
${mutableFields.map((f) => `  "${f}",`).join("\n")}
] as const
`
fs.writeFileSync(tsKeysOut, tsKeys)

console.log(`gen-bridge-schemas: wrote ${commands.length} commands, ${allKeys.length} event keys`)
NODE
